version: "3"
networks:
  internal:
    driver: bridge
services:
  vector:
    image: timberio/vector:0.11.X-alpine
    ports:
      - "8383:8383"
      - "8886:8886"
    volumes:
      - ./vector.toml:/etc/vector/vector.toml
